server:
  port: 4077
spring:
  datasource:
    ahutojforum:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://127.0.0.1:3306/ahutojforum?useUnicode=true&characterEncoding=utf-8&autoReconnect=true
      username: root
      password: cz2002610
    ahutoj:
      driver-class-name: com.mysql.cj.jdbc.Driver
      #      jdbc-url: jdbc:mysql://127.0.0.1:3306/ahutoj?useUnicode=true&characterEncoding=utf-8&autoReconnect=true
      #      username: root
      #      password: cz2002610
      jdbc-url: jdbc:mysql://81.68.182.68:3306/ahutoj?useUnicode=true&characterEncoding=utf-8&autoReconnect=true
      username: AHUTOnlinejudge
      password: 2019ahut
  redis:
    port: 6379
    host: 127.0.0.1
    database: 0
    timeout: 5000
    jedis:
      pool:
        max-wait: 1000
        max-idle: 300
        min-idle: 10
        max-active: 100
  output:
    ansi:
      enabled: always

mybatis:
  mapper-locations: classpath:com.ahutoj/dao/*.xml
  configuration:
    map-underscore-to-camel-case: true
logging:
  config: classpath:log4j2.xml